labels:
  - name: documentation
    color: BFD4F2
    description: Improvements or additions to documentation
  - name: design
    color: 5319E7
    description: UI/UX Design changes
  - name: frontend
    color: D93F0B
    description: Frontend changes
  - name: backend
    color: FBCA04
    description: Backend changes
